---
language: ruby

rvm:
- 2.0.0
- 2.1.6
- 2.2.2
- 2.4.1
- 2.5.0

before_install:
- gem install bundler

script:
- bundle exec rake test:unit
- if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then rake test:integration ; fi
- rake sanity_check

sudo: false
