---
language: ruby

rvm:
- 2.3.0
- 2.4.1
- 2.5.0
- 2.6.0

before_install:
- |
  if [[ $RUBY_VERSION == ruby-2.0* ]] || [[ $RUBY_VERSION == ruby-2.1* ]] || [[ $RUBY_VERSION == ruby-2.2* ]]  ; then
    gem install bundler -v '< 2';
  else
    gem install bundler
  fi

script:
- bundle exec rake test:unit
- if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then rake test:integration ; fi
- rake sanity_check

sudo: false
